### ISSUE TITLE
DEA review:  Replacing the References to the Council of Content Providers and Aggregators.

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/EuropeanaLicensingFramework#16]
There have been a number of comments related to the passages where we have removed the references to the nonexisting Council of Content Providers and Aggregators. Kate made it clear that she considers it undesirable that metadata specification can now be changed without consultation of an outside body. In addition it has been pointed out that the assigningment of a mediation role to the Europeana Network Association needs to be made more precise. Based on this feedback we propose the following:

1. Add the Europeana Network Association to the list of defined terms
2. Change article 7.6 to say: "All disputes arising out of or in connection with this agreement, which cannot be solved **through consensus**, shall be referred to the **Management Board of the Europeana Network Association** for mediation. The outcome of the mediation process will be binding on the parties."
3. Change Article 2.4 to say "Europeana shall ensure that future versions of the Metadata Specifications are compatible with the Metadata Specifications in place on the Effective Date. **Before mandating changes to Metadata Specifications, Europeana must consult with the Europeana Network Association.**

From our perspective it makes sense to have a precise reference to the MB in article 7.6 (the MB can always decide to involve additional people in the mediation). With regards to the reference in article 2.4 we would like to give the ENA some flexibility on how such a consultation is structured (via a task force, a specific community, the members council or otherwise) but we think that it is indeed good to keep the consultation requirement for changes to the metadata specification in place.

**Comment by KFernie** [comment]
The proposal is to replace references to the Council of Content Providers and Aggregators with the Europeana Network Association, and for the ENA to become the forum for consultations over changes to the Europeana Data Model.  I commented, and others agreed, that the EDM specification should be managed by the community of metadata experts rather than by Europeana foundation alone or the whole Europeana network.  

The issue that we need to solve is the establishment of a permanent working group to manage the development of EDM and related specifications, which can involve the necessary experts from within Europeana alongside external experts from the data community.  

My suggestion would be to refer the setting up of the working group to the Management Board of the Europeana Network Association and ask them, jointly with the Europeana Foundation, to set up a working group to take on this role.

Then Change Article 2.4 to say "Europeana shall ensure that future versions of the Metadata Specifications are compatible with the Metadata Specifications in place on the Effective Date. The Europeana Network Association Metadata working group shall be responsible for reviewing and mandating changes to Metadata Specifications, and for notifying the Network."

**Comment by paul2keller** [comment]
this has been addressed in the revised DEA. the Council is no longer referenced
